### PR TITLE
Fp

### PR DESCRIPTION
**Pull request by rdaly525**
Sorry... I merged this way too early.

Here is the original FP PR

### CODE REVIEW

**Comment by cdonovick** [comment]
reposting from https://github.com/leonardt/hwtypes/pull/30 which was merged prematurely

Not quite feature complete -- a few methods do not work for NaN / denormals -- however as lassen does not require these this should be good enough for now.

The changes to `AbstractBitVectorMeta` are an artifact of trying to use it for the metaclass of `FPVector`.  This however, turned out to not be possible for a number of reasons.  I did not revert these changes as they do not effect behavior and they make `AbstractBitVectorMeta` more extensible.  

Introduces dependency on `gmpy2` which has system dependencies `gmp`, `mpfr`, `mpc`.  Could potentially create a separate package `hwtypes[float]` so that `hwtypes` remains pure python. If we go down that route we probably should separate `hwtypes[smt]` as well.

**Comment by cdonovick** [comment]
@rsetaluri @leonardt @makaimann can you guys update your system requirements? (see https://github.com/leonardt/hwtypes/blob/fp/.travis.yml)

**Comment by leonardt** [comment]
I've added those dependencies to the `magma`, `mantle`, `pycoreir`, and `fault` travis repos. Let me know if I forgot any (we'll find out soon enough).

pycoreir has a slightly trickier setup (not using traivs addons) so verifying that it works, also with osx.  I believe the required brew command is `brew install gmp mpfr libmpc`. Can we add the `apt`/`brew` commands to the README under setup/install?

**Comment by cdonovick** [comment]
@leonardt I have updated the readme

**Comment by rdaly525** [comment]
lassen's PR: https://github.com/StanfordAHA/lassen/pull/81

**Comment by rdaly525** [comment]
I think the dependencies are:
-magma
-mantle
-fault
-pycoreir
-Cosa
-peak
-metamapper
-lassen
-garnet

**Comment by rdaly525** [comment]
peak's PR https://github.com/phanrahan/peak/pull/49

**Comment by makaimann** [comment]
CoSA’s PR: https://github.com/cristian-mattarei/CoSA/pull/84

**Comment by rdaly525** [comment]
Everyone should be able to merge their PRs now. Afterwards, this PR can be merged

**Comment by cdonovick** [comment]
@rsetaluri @rdaly525 is Garnet updated? @kuree Also does canal depend on hwtypes?

**Comment by Kuree** [comment]
It's ready to merge.

Here is the list of repos depends on `hwtypes`:
- gemstone
- canal
- garnet

The entire `gemstone` ecosystem is handled by containers so these repos are always ready to merge once the docker container is updated.

**Comment by Kuree** [comment]
Can someone merge it in and release the package? It's breaking `garnet` right now.

**Pull request merged**
