### PR TITLE
added a substitute method to SMTBit and SMTBitVector

### PR DESCRIPTION
**Pull request by rdaly525**

### CODE REVIEW

**Comment by rdaly525** [comment]
I do not think that this change affects the negative coverage. All new code paths are covered.

**Comment by cdonovick** [comment]
Is there a reason this should be a method and not a function? I am reluctant to add methods to bitvector classes as it breaks their interoperability.

**Comment by rdaly525** [comment]
It is a natural method on SMTBitVectors. What is the issue with adding methods to inherited classes from AbstractBitVector? I am not changing AbstractBitVector

**Comment by cdonovick** [comment]
We have had problems in the past with people expecting that if it works with one version of bitvector then it works with all.  Hence I would like to avoid creating cases where that is not the case but if you feel strongly that this should be a method we can pull this.

**Review by cdonovick — APPROVED** [review]
Begrudgingly

**Pull request merged**
