### PR TITLE
Make identical products return the same type

### LINKED ISSUE #76: [feature-request] Product types defined the same way should be the same object.
I Ideally would like the following to work.

```
A0 = Product.from_fields("A",{"a":int})
A1 = Product.from_fields("A",{"a":int})
assert A0 is A1

```
I do not think this would change any existing code and would be immensely helpful.

### PR DESCRIPTION
**Pull request by cdonovick**
Resolves #76

### CODE REVIEW

**Review by rdaly525 — APPROVED** [review]

**Comment by rdaly525** [comment]
@cdonovick, this breaks lassen. I am trying to investigate, but it is definitely when trying to generate magma.

EDIT:
definitely incompatible with the way that magma is doing Product

@leonardt 

```
import magma as m
class A(m.Product):
  a=m.Bit
#the above raises an error in ProductMeta._from_fields
```

**Comment by leonardt** [comment]
@rdaly525 this might be fixed by https://github.com/phanrahan/magma/commit/57dc066ffd4022d1d9d62ce558f5dd7ff3676a8c, can you try it with the latest magma master/release?

**Comment by rdaly525** [comment]
Getting a different error now! so closer...

Error from above code:
```
  File "/Users/rdaly/hwtypes/hwtypes/adt_meta.py", line 241, in __new__
    return mcs._from_fields(fields, name, bases, ns, cache, **kwargs)
TypeError: _from_fields() takes 5 positional arguments but 6 were given
```

**Comment by leonardt** [comment]
Ah, looks like that interface changed, I'll open a magma PR with the update.

**Comment by leonardt** [comment]
PR is here: https://github.com/phanrahan/magma/pull/427, running the lassen test suite now, seems to be making good progress

**Comment by rdaly525** [comment]
@leonardt once that PR is in, the GarnetFlow should be fixed for this PR

**Comment by rdaly525** [comment]
@cdonovick Can you add the exact test from #74? Other than that looks good.

**Comment by cdonovick** [comment]
Now also resolves #74

**Pull request merged**
