### PR TITLE
Simplify Product and add requested feature to Sum

### LINKED ISSUE #28: ADT feature request for Sum
Product has a nice feature in that I can get all the types it uses.

```
class Foo(Product):
  a = A
  b = B

assert Foo.a == A

```
It would be great if there was somehow an API to grab the types from a sum type as well.

```
class Foo(Sum[A,B,C])
  pass

assert Foo.Types[0] == A
```
I know that sum types are not ordered, so this does not really work. One way would be to be able to optionally have a name associated with each type (is this just a tagged union?)

I am open to other suggestions as well. Something along these lines would be very useful due to the annoyance of the family closures.

### PR DESCRIPTION
**Pull request by cdonovick**
fixes https://github.com/leonardt/hwtypes/issues/28

### CODE REVIEW

**Review by leonardt — APPROVED** [review]
LGTM

**Comment by leonardt** [comment]
Do the changes to Tuple have any affect on the interface? From what I can tell, they shouldn't, so this should be okay to merge given that the tests pass, but want to be careful that we don't break anything upstream. Maybe we can merge once someone can verify locally that the lassen tests pass?

**Comment by cdonovick** [comment]
@leonardt I assume you mean changes to Product. They should not effect any down stream code.  I ran lassen tests locally.

**Comment by cdonovick** [comment]
currently running travis with the PR https://github.com/StanfordAHA/lassen/tree/test29 https://travis-ci.com/StanfordAHA/lassen/builds/111405712

**Comment by leonardt** [comment]
Yes I meant product (rather than tuple), my mistake!

**Review by leonardt — APPROVED** [review]
LGTM and downstream lassen test run passes

**Pull request merged**
